modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="chaotic_creations"
version="1.0.0"
displayName="Chaotic Creations"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="kaiic, MCreator"
description='''
A mod that adds lots of cool gear and stuff.
'''

[[dependencies.chaotic_creations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.chaotic_creations]]
    modId="geckolib3"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


